### ISSUE TITLE
img = imresize(img, (IMG_SIZE,IMG_SIZE)).astype('float32')

### ISSUE THREAD

**Issue by kmezhoud** [Guarouba/face_rec#4]
Hi,
```scipy.misc.imresize``` is [deprecated](https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.imresize.html). 
I used ```pellow``` like this:
``` img = resize(img, [IMG_SIZE,IMG_SIZE], anti_aliasing=True) ``` 

but  can not convert it 

```astype('float32')```

any suggestion to replace this line is welcome.
Thanks

**Comment by kmezhoud** [comment]
Convert the piece of code like this:
```r
  ## convet to gray the array image
  #img = Image.fromarray(img, 'RGB').convert('L')
  img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
  ## imresize is deprecated
  #img = imresize(img, (IMG_SIZE,IMG_SIZE)).astype('float32')
  img = cv2.resize(img, dsize=(IMG_SIZE,IMG_SIZE))
#img /= 255
img = img.reshape(1,IMG_SIZE,IMG_SIZE,1)
...
```

**Comment by OlegBezverhii** [comment]
@kmezhoud - thank you so much - your code helped me
